name: Publish container image
on:
  push:

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      #- name: Setup Docker Buildx
      #  uses: docker/setup-buildx-action@v1
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: code.kevinisageek.org
          username: kevin
          password: ${{ env.FORGEJO_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: code.kevinisageek.org/kevin/mastobackup:latest
          context: mastobackup
          file: Containerfile
